
server:
  port: 8081
  servlet:
    context-path: /sicredisincronizacontas
  
spring:
  application:
    name: sicredisincronizacontas
    
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin  

sincronizador:
  rabbitmq:
    exchange: sincronizador.exchange
    routingkey: sincronizador.conta.routingkey

      
